name: C CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build the project
      - name: Build Project
        run: |
          gcc -o my_program main.c helper.c
          echo "Build completed."

      # Step 4: Run tests
      - name: Run Tests
        run: |
          ./my_program
          echo "Tests completed."
