name: CppCheck & AddressSanitizer Analysis (macOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cppcheck:
    runs-on: macos-latest  # macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --enable=all \
                 --inconclusive \
                 --std=c99 \
                 --check-library \
                 --platform=unix64 \
                 --suppress=missingIncludeSystem \
                 main.c

  address-sanitizer:
    runs-on: macos-latest  # macOS runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install compiler (if needed)
      run: brew install llvm  # Ensures you have Clang with ASan support

    - name: Compile with AddressSanitizer
      run: |
        clang -fsanitize=address -g -o my_program main.c

    - name: Run the program with AddressSanitizer
      run: |
        ASAN_OPTIONS=detect_leaks=1 ./my_program
