name: CppCheck, GoogleTest & AddressSanitizer Analysis (macOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cppcheck:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize submodules (for GoogleTest)
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: brew install cppcheck

      - name: Run cppcheck
        run: |
          cppcheck --enable=all \
                   --inconclusive \
                   --std=c99 \
                   --check-library \
                   --platform=unix64 \
                   --suppress=missingIncludeSystem \
                   main.c

  googletest:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize submodules (for GoogleTest)
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          brew install gcc

      - name: Build the project
        run: make

      - name: Run GoogleTest
        run: |
          ./my_program_test  # Your test executable

  address-sanitizer:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install compiler (if needed)
        run: brew install llvm

      - name: Build with AddressSanitizer
        run: make asan

      - name: Run the program with AddressSanitizer
        run: ./my_program  # Use the correct target executable name

      - name: Check for memory leaks (macOS)
        run: leaks -atExit -- ./my_program
