name: Build, Test, and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 3: Install Build Essentials
    - name: Install GCC and Make
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Step 4: Install Cppcheck
    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    # Step 6: Run Cppcheck Static Analysis
    - name: Run Cppcheck Static Analysis
      run: |
        make lint

    # Step 7: Build the Project (Main Program)
    - name: Build the Project
      run: |
        make clean
        make VERBOSE=1

    # Step 9: Run the Main Program
    - name: Run Main Program
      run:  |
