name: CppCheck Analysis (macOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cppcheck:
    runs-on: macos-latest  # macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cppcheck
      run: brew install cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --enable=all \
                 --inconclusive \
                 --std=c99 \
                 --check-library \
                 --platform=unix64 \
                 --suppress=missingIncludeSystem \
                 main.c
