name: CI/CD Pipeline

# Run this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Install dependencies
      - name: Install dependencies
        run: echo "Building"
        
  test:
    runs-on: ubuntu-latest

    steps:

      # Step 2: Test
      - name: Test
        run: echo "Testing"
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 5: Deploy (example of deploying to a server or hosting service)
      - name: Dummy Deploy Step
        run: echo "Deploying to the server..."
