name: CI/CD Pipeline

# Run this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Install dependencies
      - name: Install dependencies
        run: echo "Building"

      # Step 2: Run tests (basic example)
      - name: Run tests
        run: echo "Testing"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Step 5: Deploy (example of deploying to a server or hosting service)
      - name: Dummy Deploy Step
        run: echo "Deploying to the server..."
