name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up the environment
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      # Step 3: Build the project
      - name: Build Project
        run: |
          make

          gcc -o my_program src/main.c src/utils.c
          echo "Build completed."

      # Step 4: Run Tests
      - name: Run Program for Testing
        run: |
          ./my_program
          echo "Tests completed successfully."

      # Step 5: Upload Artifacts (Optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-program
          path: ./Trail
